package model.GradingTerry.AM.client;

import model.GradingTerry.AM.common.PwcOdmGradingTerry_AM;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 04 04:03:16 EDT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PwcOdmGradingTerry_AMClient extends ApplicationModuleImpl implements PwcOdmGradingTerry_AM {
    /**
     * This is the default constructor (do not remove).
     */
    public PwcOdmGradingTerry_AMClient() {
    }

    public void Exceed_TOTALQTY() {
        Object _ret =
            this.riInvokeExportedMethod(this,"Exceed_TOTALQTY",null,null);
        return;
    }
}
