package model.GradingTerry.AM.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 04 04:03:15 EDT 2017
// ---------------------------------------------------------------------
public interface PwcOdmGradingTerry_AM extends ApplicationModule {
    void Exceed_TOTALQTY();
}
