package model.GradingTerry.AM;


import model.GradingTerry.VO.PwcOdmNGGradingHeadersVOImpl;
import model.GradingTerry.VO.PwcOdmNgGradingLinesVOImpl;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 02 07:43:45 EDT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PwcOdmGradingAMImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PwcOdmGradingAMImpl() {
    }


    /**
     * Container's getter for PwcOdmNGGradingHeadersVO1.
     * @return PwcOdmNGGradingHeadersVO1
     */
    public PwcOdmNGGradingHeadersVOImpl getPwcOdmNGGradingHeadersVO1() {
        return (PwcOdmNGGradingHeadersVOImpl)findViewObject("PwcOdmNGGradingHeadersVO1");
    }

    /**
     * Container's getter for PwcOdmNgGradingLinesVO1.
     * @return PwcOdmNgGradingLinesVO1
     */
    public PwcOdmNgGradingLinesVOImpl getPwcOdmNgGradingLinesVO1() {
        return (PwcOdmNgGradingLinesVOImpl)findViewObject("PwcOdmNgGradingLinesVO1");
    }

    /**
     * Container's getter for PwcOdmGradingTerryHeaderLinesVL.
     * @return PwcOdmGradingTerryHeaderLinesVL
     */
    public ViewLinkImpl getPwcOdmGradingTerryHeaderLinesVL() {
        return (ViewLinkImpl)findViewLink("PwcOdmGradingTerryHeaderLinesVL");
    }
}
